version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: vendor_db
    environment:
      POSTGRES_USER: vendor_user
      POSTGRES_PASSWORD: vendor_pass
      POSTGRES_DB: vendor_db
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - backend_network  # ✅ ネットワークを明示

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: vendor_api
    environment:
      DB_HOST: postgres  # ✅ PostgreSQL のコンテナ名と一致
      DB_USER: vendor_user
      DB_PASSWORD: vendor_pass
      DB_NAME: vendor_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    volumes:
      - ./back:/app
    depends_on:
      - postgres
    networks:
      - backend_network  # ✅ ネットワークを明示

volumes:
  postgres_data:

networks:
  backend_network:  # ✅ 共通ネットワークを定義
    driver: bridge
